"""Generate and check deterministic OpenAPI and TypeScript contract artifacts."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

from narang_rider.api_contract import ROUTE_MANIFEST
from narang_rider.casework import CASEWORK_ROUTE_MANIFEST
from narang_rider.control_center import CONTROL_CENTER_ROUTES
from narang_rider.customer_proof import CUSTOMER_PROOF_ROUTE_MANIFEST
from narang_rider.geospatial import GEOSPATIAL_ROUTE_MANIFEST
from narang_rider.merchant_operations import MERCHANT_ROUTE_MANIFEST
from narang_rider.openapi_contract import OPERATIONS, build_openapi, canonical_bytes
from narang_rider.pilot import PILOT_ADMIN_ROUTES
from narang_rider.privacy import PRIVACY_ROUTE_MANIFEST
from narang_rider.rider_workflow import RIDER_ROUTE_MANIFEST
from narang_rider.settlement_operations import SETTLEMENT_ROUTE_MANIFEST

ROOT = Path(__file__).resolve().parents[1]
OPENAPI = ROOT / "api" / "openapi.json"
BASELINE = ROOT / "api" / "openapi.baseline.json"
DIGEST = ROOT / "api" / "openapi.sha256"
TYPESCRIPT = ROOT / "frontend" / "src" / "openapi-contract.ts"


def manifest_routes() -> set[tuple[str, str]]:
    routes: set[tuple[str, str]] = set()
    object_manifests = (
        ROUTE_MANIFEST,
        CUSTOMER_PROOF_ROUTE_MANIFEST,
        GEOSPATIAL_ROUTE_MANIFEST,
        MERCHANT_ROUTE_MANIFEST,
        RIDER_ROUTE_MANIFEST,
    )
    for manifest in object_manifests:
        routes.update(
            (item.method.upper(), getattr(item, "path_template", getattr(item, "path", "")))
            for item in manifest
        )
    routes.update((item.method.upper(), item.path) for item in PILOT_ADMIN_ROUTES)
    routes.update((method, path) for method, path, *_ in CONTROL_CENTER_ROUTES)
    routes.update((method, path) for method, path, *_ in SETTLEMENT_ROUTE_MANIFEST)
    for manifest in (PRIVACY_ROUTE_MANIFEST, CASEWORK_ROUTE_MANIFEST):
        for key in manifest:
            method, path = key.split(" ", 1)
            routes.add((method, path))
    return routes


def typescript_contract() -> str:
    lines = [
        "// Generated by scripts/generate_openapi.py; do not hand edit.",
        "export const openApiOperations = {",
    ]
    for operation in sorted(OPERATIONS, key=lambda item: item.operation_id):
        lines.append(
            f'  {operation.operation_id}: {{ method: "{operation.method}", path: "{operation.path}" }},'
        )
    lines.extend(
        ("} as const;", "", "export type OpenApiOperationId = keyof typeof openApiOperations;", "")
    )
    return "\n".join(lines)


def generated() -> dict[Path, bytes]:
    document = build_openapi()
    api_bytes = canonical_bytes(document)
    declared = {(item.method, item.path) for item in OPERATIONS}
    missing = sorted(manifest_routes() - declared)
    if missing:
        raise SystemExit(f"route manifest drift is not represented in OpenAPI: {missing}")
    return {
        OPENAPI: api_bytes,
        DIGEST: f"{hashlib.sha256(api_bytes).hexdigest()}  openapi.json\n".encode(),
        TYPESCRIPT: typescript_contract().encode(),
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--accept-baseline", action="store_true")
    args = parser.parse_args()
    artifacts = generated()
    if args.write:
        for path, content in artifacts.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(content)
        if args.accept_baseline:
            BASELINE.write_bytes(artifacts[OPENAPI])
        return
    for path, expected in artifacts.items():
        if not path.exists() or path.read_bytes() != expected:
            raise SystemExit(f"stale generated contract: {path.relative_to(ROOT)}")
    if not BASELINE.exists():
        raise SystemExit("OpenAPI compatibility baseline is missing")
    current = json.loads(artifacts[OPENAPI])
    baseline = json.loads(BASELINE.read_text(encoding="utf-8"))
    old_operations = {(path, method) for path, item in baseline["paths"].items() for method in item}
    new_operations = {(path, method) for path, item in current["paths"].items() for method in item}
    removed = sorted(old_operations - new_operations)
    if removed:
        raise SystemExit(f"breaking API removal requires explicit version/review: {removed}")
    if baseline["info"]["version"] != current["info"]["version"]:
        raise SystemExit("API version change requires explicit reviewed baseline update")
    print(f"OpenAPI contract valid: {len(new_operations)} operations")


if __name__ == "__main__":
    main()
